# frozen_string_literal: true
require 'zap_message/error'
require 'zap_message/validator'

require 'zap_message/model/base'
require 'zap_message/model/media'
require 'zap_message/model/message'
# TODO: implement
# require 'zap_message/model/address_message'
require 'zap_message/model/audio_message'
require 'zap_message/model/contacts_message'
require 'zap_message/model/document_message'
# TODO: implement
require 'zap_message/model/flow_message'
require 'zap_message/model/image_message'
require 'zap_message/model/interactive_cta_message'
require 'zap_message/model/interactive_list_message'
require 'zap_message/model/interactive_reply_button_message'
require 'zap_message/model/location_message'
require 'zap_message/model/location_request_message'
require 'zap_message/model/reaction_message'
require 'zap_message/model/read_receipt_message'
require 'zap_message/model/sticker_message'
require 'zap_message/model/template_message'
require 'zap_message/model/text_message'
require 'zap_message/model/video_message'
